CREATE TABLE `hip2dat` (
  `ID` int(10) unsigned NOT NULL,
  `Sn` tinyint(3) unsigned NOT NULL,
  `So` tinyint(3) unsigned NOT NULL,
  `nC` tinyint(3) unsigned NOT NULL,
  `RA` float NOT NULL,
  `Decl` float NOT NULL,
  `Plx` float NOT NULL,
  `PMRA` float NOT NULL,
  `PMDec` float NOT NULL,
  `eRA` float NOT NULL,
  `eDecl` float NOT NULL,
  `ePlx` float NOT NULL,
  `ePMRA` float NOT NULL,
  `ePMDec` float NOT NULL,
  `nFT` smallint(5) unsigned NOT NULL,
  `F2` float NOT NULL,
  `F1` tinyint(3) unsigned NOT NULL,
  `cda` float NOT NULL,
  `catID` smallint(5) unsigned NOT NULL,
  `Mag` float NOT NULL,
  `eMag` float NOT NULL,
  `sMag` float NOT NULL,
  `VA` tinyint(3) unsigned NOT NULL,
  `BV` float NOT NULL,
  `eBV` float NOT NULL,
  `VI` float NOT NULL,
  `UW1` float NOT NULL,
  `UW2` float NOT NULL,
  `UW3` float NOT NULL,
  `UW4` float NOT NULL,
  `UW5` float NOT NULL,
  `UW6` float NOT NULL,
  `UW7` float NOT NULL,
  `UW8` float NOT NULL,
  `UW9` float NOT NULL,
  `UW10` float NOT NULL,
  `UW11` float NOT NULL,
  `UW12` float NOT NULL,
  `UW13` float NOT NULL,
  `UW14` float NOT NULL,
  `UW15` float NOT NULL,
  PRIMARY KEY (`ID`)
);
