CREATE TABLE `bsc5dat` (
  `HR` smallint unsigned NOT NULL,
  `BF` varchar(10) DEFAULT NULL,
  `DMId` varchar(11) DEFAULT NULL,
  `HD` mediumint unsigned DEFAULT NULL,
  `SAO` mediumint unsigned DEFAULT NULL,
  `FK5` smallint unsigned DEFAULT NULL,
  `IRFlag` char(1) DEFAULT NULL,
  `IRCode` char(1) DEFAULT NULL,
  `MultCode` char(1) DEFAULT NULL,
  `ADS` smallint unsigned DEFAULT NULL,
  `ADSnc` varchar(2) DEFAULT NULL,
  `VarID` varchar(9) DEFAULT NULL,
  `RAh19` tinyint unsigned DEFAULT NULL,
  `RAm19` tinyint unsigned DEFAULT NULL,
  `RAs19` decimal(3,1) DEFAULT NULL,
  `Declb19` char(1) DEFAULT NULL,
  `Decld19` tinyint unsigned DEFAULT NULL,
  `Declm19` tinyint unsigned DEFAULT NULL,
  `Decls19` tinyint unsigned DEFAULT NULL,
  `RAh20` tinyint unsigned DEFAULT NULL,
  `RAm20` tinyint unsigned DEFAULT NULL,
  `RAs20` decimal(3,1) DEFAULT NULL,
  `Declb20` char(1) DEFAULT NULL,
  `Decld20` tinyint unsigned DEFAULT NULL,
  `Declm20` tinyint unsigned DEFAULT NULL,
  `Decls20` tinyint unsigned DEFAULT NULL,
  `GLong` decimal(5,2) DEFAULT NULL,
  `GLat` decimal(4,2) DEFAULT NULL,
  `Vmag` decimal(3,2) DEFAULT NULL,
  `VmagCode` char(1) DEFAULT NULL,
  `VmagFlag` char(1) DEFAULT NULL,
  `BV` decimal(3,2) DEFAULT NULL,
  `BVFlag` char(1) DEFAULT NULL,
  `UB` decimal(3,2) DEFAULT NULL,
  `UBFlag` char(1) DEFAULT NULL,
  `RI` decimal(3,2) DEFAULT NULL,
  `RICode` char(1) DEFAULT NULL,
  `Spectrum` varchar(20) DEFAULT NULL,
  `SpectrumCode` char(1) DEFAULT NULL,
  `PMRA` decimal(4,3) DEFAULT NULL,
  `PMDec` decimal(4,3) DEFAULT NULL,
  `PlxFlag` char(1) DEFAULT NULL,
  `Plx` decimal(4,3) DEFAULT NULL,
  `RadVel` smallint DEFAULT NULL,
  `RadVelCom` varchar(4) DEFAULT NULL,
  `RotVelLim` varchar(2) DEFAULT NULL,
  `RotVel` smallint DEFAULT NULL,
  `RotVelFlag` char(1) DEFAULT NULL,
  `Dmag` decimal(3,1) DEFAULT NULL,
  `Sep` decimal(5,1) DEFAULT NULL,
  `MultID` varchar(4) DEFAULT NULL,
  `MultNum` tinyint DEFAULT NULL,
  `NoteFlag` char(1) DEFAULT NULL,
  PRIMARY KEY (`HR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
